variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
variable "profile" {}
variable "vcn_cidr_block" {}
variable "vcn_display_name" {}
variable "vcn_dns_label" {}
variable "internet_gateway_display_name" {}
variable "nat_gateway_display_name" {}
variable "analytics_instance_capacity_capacity_type" {}
variable "analytics_instance_capacity_capacity_value" {}
variable "analytics_instance_feature_set" {}
variable "analytics_instance_idcs_access_token" {}
variable "analytics_instance_license_type" {}
variable "analytics_instance_name" {}
variable "analytics_instance_description" {}
variable "analytics_instance_email_notification" {}
variable "analytics_instance_network_endpoint_details_network_endpoint_type" {}
variable "analytics_instance_network_endpoint_details_whitelisted_ips" {}
variable "public_subnet_display_name" {}
variable "public_subnet_cidr_block" {}